var exports = exports || this;
exports.FontAwesome = (function(global){
	var K = function(){};

	var FontAwesome = function() {
		var self;

		if (this instanceof FontAwesome) {
			self = this;
		} else {
			self = new K();
		}

		self.charcode = {
			glass: String.fromCharCode(0xf000),
			music: String.fromCharCode(0xf001),
			search: String.fromCharCode(0xf002),
			envelope: String.fromCharCode(0xf003),
			heart: String.fromCharCode(0xf004),
			star: String.fromCharCode(0xf005),
			starEmpty: String.fromCharCode(0xf006),
			user: String.fromCharCode(0xf007),
			film: String.fromCharCode(0xf008),
			thLarge: String.fromCharCode(0xf009),
			th: String.fromCharCode(0xf00a),
			thList: String.fromCharCode(0xf00b),
			ok: String.fromCharCode(0xf00c),
			remove: String.fromCharCode(0xf00d),
			zoomIn: String.fromCharCode(0xf00e),
			zoomOut: String.fromCharCode(0xf010),
			off: String.fromCharCode(0xf011),
			signal: String.fromCharCode(0xf012),
			cog: String.fromCharCode(0xf013),
			trash: String.fromCharCode(0xf014),
			home: String.fromCharCode(0xf015),
			file: String.fromCharCode(0xf016),
			time: String.fromCharCode(0xf017),
			road: String.fromCharCode(0xf018),
			downloadAlt: String.fromCharCode(0xf019),
			download: String.fromCharCode(0xf01a),
			upload: String.fromCharCode(0xf01b),
			inbox: String.fromCharCode(0xf01c),
			playCircle: String.fromCharCode(0xf01d),
			repeat: String.fromCharCode(0xf01e),
			refresh: String.fromCharCode(0xf021),
			listAlt: String.fromCharCode(0xf022),
			lock: String.fromCharCode(0xf023),
			flag: String.fromCharCode(0xf024),
			headphones: String.fromCharCode(0xf025),
			volumeOff: String.fromCharCode(0xf026),
			volumeDown: String.fromCharCode(0xf027),
			volumeUp: String.fromCharCode(0xf028),
			qrcode: String.fromCharCode(0xf029),
			barcode: String.fromCharCode(0xf02a),
			tag: String.fromCharCode(0xf02b),
			tags: String.fromCharCode(0xf02c),
			book: String.fromCharCode(0xf02d),
			bookmark: String.fromCharCode(0xf02e),
			print: String.fromCharCode(0xf02f),
			camera: String.fromCharCode(0xf030),
			font: String.fromCharCode(0xf031),
			bold: String.fromCharCode(0xf032),
			italic: String.fromCharCode(0xf033),
			textHeight: String.fromCharCode(0xf034),
			textWidth: String.fromCharCode(0xf035),
			alignLeft: String.fromCharCode(0xf036),
			alignCenter: String.fromCharCode(0xf037),
			alignRight: String.fromCharCode(0xf038),
			alignJustify: String.fromCharCode(0xf039),
			list: String.fromCharCode(0xf03a),
			indentLeft: String.fromCharCode(0xf03b),
			indentRight: String.fromCharCode(0xf03c),
			facetimeVideo: String.fromCharCode(0xf03d),
			picture: String.fromCharCode(0xf03e),
			pencil: String.fromCharCode(0xf040),
			mapMarker: String.fromCharCode(0xf041),
			adjust: String.fromCharCode(0xf042),
			tint: String.fromCharCode(0xf043),
			edit: String.fromCharCode(0xf044),
			share: String.fromCharCode(0xf045),
			check: String.fromCharCode(0xf046),
			move: String.fromCharCode(0xf047),
			stepBackward: String.fromCharCode(0xf048),
			fastBackward: String.fromCharCode(0xf049),
			backward: String.fromCharCode(0xf04a),
			play: String.fromCharCode(0xf04b),
			pause: String.fromCharCode(0xf04c),
			stop: String.fromCharCode(0xf04d),
			forward: String.fromCharCode(0xf04e),
			fastForward: String.fromCharCode(0xf050),
			stepForward: String.fromCharCode(0xf051),
			eject: String.fromCharCode(0xf052),
			chevronLeft: String.fromCharCode(0xf053),
			chevronRight: String.fromCharCode(0xf054),
			plusSign: String.fromCharCode(0xf055),
			minusSign: String.fromCharCode(0xf0056),
			removeSign: String.fromCharCode(0xf057),
			okSign: String.fromCharCode(0xf058),
			questionSign: String.fromCharCode(0xf059),
			infoSign: String.fromCharCode(0xf05a),
			screenshot: String.fromCharCode(0xf05b),
			removeCircle: String.fromCharCode(0xf05c),
			okCircle: String.fromCharCode(0xf05d),
			banCircle: String.fromCharCode(0xf05e),
			arrowLeft: String.fromCharCode(0xf060),
			arrowRight: String.fromCharCode(0xf061),
			arrowUp: String.fromCharCode(0xf062),
			arrowDown: String.fromCharCode(0xf063),
			shareAlt: String.fromCharCode(0xf064),
			resizeFull: String.fromCharCode(0xf065),
			resizeSmall: String.fromCharCode(0xf066),
			plus: String.fromCharCode(0xf067),
			minus: String.fromCharCode(0xf068),
			asterisk: String.fromCharCode(0xf069),
			exclamationSign: String.fromCharCode(0xf06a),
			gift: String.fromCharCode(0xf06b),
			leaf: String.fromCharCode(0xf06c),
			fire: String.fromCharCode(0xf06d),
			eyeOpen: String.fromCharCode(0xf06e),
			eyeClose: String.fromCharCode(0xf070),
			warningSign: String.fromCharCode(0xf071),
			plane: String.fromCharCode(0xf072),
			calendar: String.fromCharCode(0xf073),
			random: String.fromCharCode(0xf074),
			comment: String.fromCharCode(0xf075),
			magnet: String.fromCharCode(0xf076),
			chevronUp: String.fromCharCode(0xf077),
			chevronDown: String.fromCharCode(0xf078),
			retweet: String.fromCharCode(0xf079),
			shoppingCart: String.fromCharCode(0xf07a),
			folderClose: String.fromCharCode(0xf07b),
			folderOpen: String.fromCharCode(0xf07c),
			resizeVertical: String.fromCharCode(0xf07d),
			resizeHorizontal: String.fromCharCode(0xf07e),
			barChart: String.fromCharCode(0xf080),
			twitterSign: String.fromCharCode(0xf081),
			facebookSign: String.fromCharCode(0xf082),
			cameraRetro: String.fromCharCode(0xf083),
			key: String.fromCharCode(0xf084),
			cogs: String.fromCharCode(0xf085),
			comments: String.fromCharCode(0xf086),
			thumbsUp: String.fromCharCode(0xf087),
			thumbsDown: String.fromCharCode(0xf088),
			starHalf: String.fromCharCode(0xf089),
			heartEmpty: String.fromCharCode(0xf08a),
			signout: String.fromCharCode(0xf08b),
			linkedinSign: String.fromCharCode(0xf08c),
			pushpin: String.fromCharCode(0xf08d),
			externalLink: String.fromCharCode(0xf08e),
			signin: String.fromCharCode(0xf090),
			trophy: String.fromCharCode(0xf091),
			githubSign: String.fromCharCode(0xf092),
			uploadAlt: String.fromCharCode(0xf093),
			lemon: String.fromCharCode(0xf094),
			phone: String.fromCharCode(0xf095),
			checkEmpty: String.fromCharCode(0xf096),
			bookmarkEmpty: String.fromCharCode(0xf097),
			phoneSign: String.fromCharCode(0xf098),
			twitter: String.fromCharCode(0xf099),
			facebook: String.fromCharCode(0xf09a),
			github: String.fromCharCode(0xf09b),
			unlock: String.fromCharCode(0xf09c),
			creditCard: String.fromCharCode(0xf09d),
			rss: String.fromCharCode(0xf09e),
			hdd: String.fromCharCode(0xf0a0),
			bullhorn: String.fromCharCode(0xf0a1),
			bell: String.fromCharCode(0xf0a2),
			certificate: String.fromCharCode(0xf0a3),
			handRight: String.fromCharCode(0xf0a4),
			handLeft: String.fromCharCode(0xf0a5),
			handUp: String.fromCharCode(0xf0a6),
			handDown: String.fromCharCode(0xf0a7),
			circleArrowLeft: String.fromCharCode(0xf0a8),
			circleArrowRight: String.fromCharCode(0xf0a9),
			circleArrowUp: String.fromCharCode(0xf0aa),
			circleArrowDown: String.fromCharCode(0xf0ab),
			globe: String.fromCharCode(0xf0ac),
			wrench: String.fromCharCode(0xf0ad),
			tasks: String.fromCharCode(0xf0ae),
			filter: String.fromCharCode(0xf0b0),
			briefcase: String.fromCharCode(0xf0b1),
			fullscreen: String.fromCharCode(0xf0b2),
			group: String.fromCharCode(0xf0c0),
			link: String.fromCharCode(0xf0c1),
			cloud: String.fromCharCode(0xf0c2),
			beaker: String.fromCharCode(0xf0c3),
			cut: String.fromCharCode(0xf0c4),
			copy: String.fromCharCode(0xf0c5),
			paperClip: String.fromCharCode(0xf0c6),
			save: String.fromCharCode(0xf0c7),
			signBlank: String.fromCharCode(0xf0c8),
			reorder: String.fromCharCode(0xf0c9),
			listUl: String.fromCharCode(0xf0ca),
			listOl: String.fromCharCode(0xf0cb),
			strikethrough: String.fromCharCode(0xf0cc),
			underline: String.fromCharCode(0xf0cd),
			table: String.fromCharCode(0xf0ce),
			magic: String.fromCharCode(0xf0d0),
			truck: String.fromCharCode(0xf0d1),
			pinterest: String.fromCharCode(0xf0d2),
			pinterestSign: String.fromCharCode(0xf0d3),
			googlePlusSign: String.fromCharCode(0xf0d4),
			googlePlus: String.fromCharCode(0xf0d5),
			money: String.fromCharCode(0xf0d6),
			caretDown: String.fromCharCode(0xf0d7),
			caretUp: String.fromCharCode(0xf0d8),
			caretLeft: String.fromCharCode(0xf0d9),
			caretRight: String.fromCharCode(0xf0da),
			columns: String.fromCharCode(0xf0db),
			sort: String.fromCharCode(0xf0dc),
			sortDown: String.fromCharCode(0xf0dd),
			sortUp: String.fromCharCode(0xf0de),
			envelopeAll: String.fromCharCode(0xf0e0),
			linkedin: String.fromCharCode(0xf0e1),
			undo: String.fromCharCode(0xf0e2),
			legal: String.fromCharCode(0xf0e3),
			dashboard: String.fromCharCode(0xf0e4),
			commentAlt: String.fromCharCode(0xf0e5),
			commentsAlt: String.fromCharCode(0xf0e6),
			bolt: String.fromCharCode(0xf0e7),
			sitemap: String.fromCharCode(0xf0e8),
			umbrella: String.fromCharCode(0xf0e9),
			paste: String.fromCharCode(0xf0ea),
			userMd: String.fromCharCode(0xf200)
		};

		return self;
	};

	K.prototype = FontAwesome.prototype;

	FontAwesome.prototype.icon = function(options){
		var self = this;

		if (options instanceof Array) {
			var icons = [];

			options.forEach(function(value){
				icons.push(self.charcode[value]);
			});

			return icons;
		} else {
			return self.charcode[options];
		}
	};

	return FontAwesome;
})(this);
